Website/OCM.Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using OCM.API.Common;
using OCM.API.Common.Model;
using System;

namespace OCM.MVC.Controllers
{
    public class AboutController : BaseController
    {
        IWebHostEnvironment _host;

        //
        // GET: /About/

        public AboutController(IWebHostEnvironment host)
        {
            _host = host;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }

        /// <summary>
        /// /Contact
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Guidance()
        {
            return View();
        }

        public ActionResult Funding()
        {
            return View();
        }

        public ActionResult DataSharing()
        {
            var countryList = new ReferenceDataManager().GetCountries(false);
            ViewBag.CountryList = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(countryList, "ID", "Title");
            return View(new DataSharingAgreement {  CountryID=2});
        }

        [HttpPost]
        [Authorize(Roles = "StandardUser")]
        public ActionResult DataSharing(DataSharingAgreement agreement)
        {

            var countryList = new ReferenceDataManager().GetCountries(false);
            ViewBag.CountryList = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(countryList, "ID", "Title");

            if (ModelState.IsValid)
            {

                var submissionManager = new SubmissionManager();
                bool savedOK = submissionManager.SubmitDataAgreement(agreement, (int)UserID);

                if (!savedOK)
                {
                    ViewBag.ErrorMessage = "Please check you have filled out all of the fields. All information is required.";
                }
                else
                {
                    ViewBag.Submitted = true;
                }


            }

            return View(agreement);
        }


        /// <summary>
        /// /contact/ post new contact us mesage
        /// </summary>
        /// <param name="album"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Contact(ContactSubmission contactSubmission)
        {
            if (ModelState.IsValid)
            {
                //check for spam bot by discarding submissions which populate phone field
                if (String.IsNullOrEmpty(contactSubmission.Phone))
                {
                    SubmissionManager submissionManager = new SubmissionManager();
                    bool sentOK = submissionManager.SubmitContactSubmission(contactSubmission);

                    if (!sentOK)
                    {
                        ViewBag.ErrorMessage = "There was a problem sending your message";
                    }
                }
                return RedirectToAction("ContactSubmitted");
            }

            return View(contactSubmission);
        }

        /// <summary>
        /// view shown after contact message submitted
        /// </summary>
        /// <returns></returns>
        public ActionResult ContactSubmitted()
        {
            return View();
        }
    }
}

Website/OCM.Web/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using OCM.API.Common;
using OCM.API.Common.DataSummary;
using System;
using System.Collections.Generic;
using System.Linq;


namespace OCM.MVC.Controllers
{
    public class CountryController : Controller
    {
        // GET: Country and /Country/UnitedKingdom
        //[OutputCache(Duration = 60, VaryByParam = "countryname")]
        public ActionResult Index(string countryname)
        {
            using (var refDataManager = new ReferenceDataManager())
            {

                if (!String.IsNullOrEmpty(countryname))
                {

                    var country = refDataManager.GetCountryByName(countryname);
                    return this.Summary(countryname);
                }

                //list of all countries
                var allCountries = refDataManager.GetCountries(false);
                using (var dataSummaryManager = new DataSummaryManager())
                {
                    var countryStats = dataSummaryManager.GetAllCountryStats();

                    var continents = new Dictionary<string, string>();
                    continents.Add("AS", "Asia");
                    continents.Add("EU", "Europe");
                    continents.Add("NA", "North America");
                    continents.Add("OC", "Oceania");
                    continents.Add("SA", "South America");
                    continents.Add("AF", "Africa");

                    ViewBag.Continents = continents;
                    ViewBag.CountryStats = countryStats;
                }
                return View(allCountries);
            }
        }

        public ActionResult Summary(string countryname)
        {

            return View();
        }

        [Route("country/{countryname}/networks")]
        //[OutputCache(Duration = 60, VaryByParam = "countryname")]
        public ActionResult Networks(string countryname)
        {
            using (var refDataManager = new ReferenceDataManager())
            {
                var country = refDataManager.GetCountryByName(countryname);
                if (country != null)
                {
                    //int[] genericOperatorIds = { 1, 44, 45 };
                    var operators = refDataManager.GetOperators(country.ID).Where(o => o.ID != 1 && o.ID != 44 && o.ID != 45).ToList();
                    ViewBag.Country = country;
                    return View(operators);
                }
                return View();
            }
        }
    }
}

Website/OCM.Web/Controllers/POIController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using OCM.API.Common;
using OCM.API.Common.DataSummary;
using OCM.API.Common.Model;
using OCM.Core.Common;
using OCM.Core.Settings;
using OCM.MVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace OCM.MVC.Controllers
{
    public class POIController : BaseController
    {
        // GET: /POI/
        private IHostEnvironment _host;
        private IMemoryCache _cache;

        private CoreSettings _settings;
        public POIController(IHostEnvironment host, IMemoryCache memoryCache, IConfiguration config)
        {
            _host = host;
            _cache = memoryCache;

            _settings = GetSettingsFromConfig(config);
        }

        private CoreReferenceData GetCoreReferenceData()
        {
            return GetCoreReferenceDataAsync().Result;
        }

        private async Task<CoreReferenceData> GetCoreReferenceDataAsync()
        {
            if (_cache.TryGetValue("_coreRefData", out var refData))
            {
                return refData as CoreReferenceData;
            }
            else
            {
                using (var refDataManager = new OCM.API.Common.ReferenceDataManager())
                {
                    var result = await refDataManager.GetCoreReferenceDataAsync();
                    _cache.Set("_coreRefData", result);
                    return result;
                }
            }
        }

        public async Task<ActionResult> Index(POIBrowseModel filter)
        {
            if (filter?.ReferenceData == null)
            {
                if (filter == null)
                {
                    filter = new POIBrowseModel();
                    filter.ShowAdvancedOptions = true;
                }
                filter.ReferenceData = await GetCoreReferenceDataAsync();

            }

            var cpManager = new API.Common.POIManager();

            //dropdown selections of -1 represent an intended null selection, fix this by nulling relevant items
            filter.CountryIDs = this.ConvertNullableSelection(filter.CountryIDs);
            filter.LevelIDs = this.ConvertNullableSelection(filter.LevelIDs);
            filter.ConnectionTypeIDs = this.ConvertNullableSelection(filter.ConnectionTypeIDs);
            filter.OperatorIDs = this.ConvertNullableSelection(filter.OperatorIDs);
            filter.StatusTypeIDs = this.ConvertNullableSelection(filter.StatusTypeIDs);
            filter.UsageTypeIDs = this.ConvertNullableSelection(filter.UsageTypeIDs);
            filter.DataProviderIDs = this.ConvertNullableSelection(filter.DataProviderIDs);
            filter.SubmissionStatusTypeID = this.ConvertNullableSelection(filter.SubmissionStatusTypeID);

            filter.IncludeComments = true;

            if (IsRequestByRobot)
            {
                //force mirror db when browser is a robot
                filter.AllowMirrorDB = true;
                filter.AllowDataStoreDB = false;
            }

            if (!String.IsNullOrWhiteSpace(filter.Country))
            {
                //TODO: cache country id lookup
                using (var refData = new OCM.API.Common.ReferenceDataManager())
                {
                    var countrySelected = refData.GetCountryByName(filter.Country);
                    if (countrySelected != null)
                    {
                        filter.CountryIDs = new int[] { countrySelected.ID };
                    }
                }
            }
            else
            {
                //default to UK
                // if (filter.CountryIDs == null) filter.CountryIDs = new int[] { 1 };
            }

            filter.MaxResults = 100;

            if (!String.IsNullOrWhiteSpace(filter.SearchLocation))
            {
                if (filter.SearchLocation.ToUpper().StartsWith("OCM-")) filter.SearchLocation = filter.SearchLocation.Replace("OCM-", "");
                if (filter.SearchLocation.ToUpper().StartsWith("OCM")) filter.SearchLocation = filter.SearchLocation.Replace("OCM", "");

                if (IsNumeric(filter.SearchLocation.Trim()))
                {
                    int poiID = -1;
                    //treat numbers as OCM ref
                    if (int.TryParse(filter.SearchLocation.Trim(), out poiID))
                    {
                        filter.ChargePointIDs = new int[] { poiID };
                    }
                }
                else
                {
                    //attempt to geocode
                    var geocode = new GeocodingHelper(_settings);
                    string searchCountryName = null;
                    if (filter.CountryIDs != null && filter.CountryIDs.Count() > 0)
                    {
                        var searchCountry = filter.ReferenceData.Countries.FirstOrDefault(c => c.ID == filter.CountryIDs[0]);
                        searchCountryName = searchCountry.Title;
                    }

                    API.Common.Model.Extended.GeocodingResult position = null;

                    // FIXME: geocoding is disabled, find an laternative service to use
                    //geocode.GeolocateAddressInfo_Google(filter.SearchLocation.Trim() + (searchCountryName != null ? ", " + searchCountryName : ""));

                    if (filter.SearchLocation.Contains(","))
                    {
                        var vals = filter.SearchLocation.Split(',');
                        if (IsNumeric(vals[0]) && IsNumeric(vals[1]))
                        {
                            position = new API.Common.Model.Extended.GeocodingResult
                            {
                                Latitude = double.Parse(vals[0]),
                                Longitude = double.Parse(vals[1])
                            };
                        }
                    }
                    if (position != null)
                    {
                        filter.Latitude = position.Latitude;
                        filter.Longitude = position.Longitude;
                        if (filter.Distance == null) filter.Distance = 50;
                        filter.DistanceUnit = API.Common.Model.DistanceUnit.Miles;
                        //TODO: distance unit KM
                        //if (distanceunit == "km") searchfilters.DistanceUnit = API.Common.Model.DistanceUnit.KM;

                        ViewBag.FormattedAddress = position.Address ?? "";
                    }
                }
            }

            filter.POIList = (await cpManager.GetPOIListAsync((OCM.API.Common.APIRequestParams)filter, filter.ReferenceData)).ToList();
            return View(filter);
        }

        private int[] ConvertNullableSelection(int[] selectedItems)
        {
            if (selectedItems != null)
            {
                var list = selectedItems.ToList();
                list.RemoveAll(i => i == -1);
                if (list.Count > 0)
                {
                    return list.ToArray();
                }
            }
            return (int[])null;
        }

        private bool IsNumeric(string text)
        {
            Regex regex = new Regex(@"^[-+]?[0-9]*\.?[0-9]+$");
            return regex.IsMatch(text);
        }

        // GET: /POI/Details/5

        //[OutputCache(Duration=240, VaryByParam="id")]
        public async Task<ActionResult> Details(int id = 0, string layout = null, string status = null)
        {
            if (id <= 0) return RedirectToAction("Index");

            if (status != null) ViewBag.Status = status;

            OCM.API.Common.POIManager cpManager = new API.Common.POIManager();
            POIViewModel viewModel = new POIViewModel();

            var poi = await cpManager.Get(id, true, allowDiskCache: false, allowMirrorDB: true);
            if (poi != null)
            {
                ViewBag.FullTitle = "Location Details: OCM-" + poi.ID + " " + poi.AddressInfo.Title;

                List<LocationImage> imageList = null; // new OCM.MVC.App_Code.GeocodingHelper().GetGeneralLocationImages((double)poi.AddressInfo.Latitude, (double)poi.AddressInfo.Longitude);

                if (imageList != null)
                {
                    imageList = imageList.Where(i => i.Width >= 500).ToList();
                    ViewBag.ImageList = imageList.ToList();
                }

                viewModel.POI = poi;

                if (!IsRequestByRobot)
                {
                    viewModel.NewComment = new UserComment() { ChargePointID = poi.ID, CommentType = new UserCommentType { ID = 10 }, CheckinStatusType = new CheckinStatusType { ID = 0 } };

                    System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
                    sw.Start();
                    viewModel.POIListNearby = (await cpManager.GetPOIListAsync(new APIRequestParams { MaxResults = 10, Latitude = poi.AddressInfo.Latitude, Longitude = poi.AddressInfo.Longitude, Distance = 15, DistanceUnit = DistanceUnit.Miles, AllowMirrorDB = true })).ToList();
                    viewModel.POIListNearby.RemoveAll(p => p.ID == poi.ID); //don't include the current item in nearby POI list
                    sw.Stop();
                    System.Diagnostics.Debug.WriteLine(sw.ElapsedMilliseconds);

                    ViewBag.ReferenceData = new POIBrowseModel(await GetCoreReferenceDataAsync());

                    //get data quality report

                    //if (IsUserAdmin)
                    //{
                    viewModel.DataQualityReport = new DataAnalysisManager().GetDataQualityReport(poi);
                    //}

                    ViewBag.UserCanEditPOI = false;
                    if (IsUserSignedIn)
                    {

Website/OCM.Web/Views/Country/Index.cshtml
@model IEnumerable<OCM.API.Common.Model.Country>

@{
    ViewBag.Title = "Countries";
    var continents = (Dictionary<string, string>)ViewBag.Continents;
    var countryStats = (List<OCM.API.Common.DataSummary.CountrySummary>)ViewBag.CountryStats;
}

<h2>All Countries</h2>

<p>
    We have information on charging locations in the following countries, if your country is not listed we need you to <a href="@Url.Action("Add","POI")">add the locations</a> you know about.
</p>
@Html.Partial("~/Views/Widget/_GeoChartWidget.cshtml")
<div>

    @foreach (var continent in continents)
    {
        <h1>@continent.Value</h1>

        foreach (var item in Model.Where(c => c.ContinentCode == continent.Key))
        {
            var countryNameParam = item.Title.Replace(" ", "").ToLower();
            var countryStat = countryStats.FirstOrDefault(c => c.ISOCode == item.ISOCode);

            if (countryStat != null)
            {
                <div class="well well-sm" style="display:inline-block;margin:1em;">
                    <h3><a id="@item.ISOCode"></a>@Html.DisplayFor(modelItem => item.Title)</h3>
                    <ul>
                        <li><a href="@Url.Action("Index", "POI", new { CountryIDs=item.ID, CountryName=countryNameParam})">@countryStat.StationCount charging stations in @countryStat.LocationCount locations</a></li>
                        <li><a href="@Url.Content("~/country/" +countryNameParam +"/networks")">Networks</a></li>
                    </ul>
                </div>
            }

        }
    }
</div>

Website/OCM.Web/Views/Country/Networks.cshtml
@model IEnumerable<OCM.API.Common.Model.OperatorInfo>

@{
   
    var country = (OCM.API.Common.Model.Country)ViewBag.Country;

    var countryName = (country.Title.StartsWith("United") ? " the " + country.Title : country.Title);
    ViewBag.Title = "Charging Networks in "+countryName;
}



<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home")">Home</a></li>
    <li><a href="@Url.Action("Index","Country")">Countries</a></li>
    <li><a href="#">@country.Title</a></li>
    <li class="active">Networks</li>
</ol>

<h1>Charging Networks in @countryName</h1>


@if (Model != null && Model.Count() > 0)
{
    <p>The following charging networks are known to operate in @countryName. If you can see that one is missing, please @Html.ActionLink("Contact Us", "Contact", "About").</p>
    
    <div>
        @foreach (var item in Model)
        {

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">@Html.DisplayFor(modelItem => item.Title) <small><a href="@Url.Action("Index","POI",new {CountryIds=country.ID, OperatorIds=item.ID})">View <strong>@Html.DisplayFor(modelItem => item.Title)</strong> Charging Locations in @countryName</a></small></h3>
                </div>
                <div class="panel-body">
                    <p class="pull-right">@Html.DisplayFor(modelItem => item.Comments)</p>
                    <dl class="dl-horizontal">
                        @if (item.WebsiteURL != null)
                        {
                            <dt>Website</dt>
                            <dd>@Html.DisplayFor(modelItem => item.WebsiteURL)</dd>
                        }
                        @if (item.PhonePrimaryContact != null)
                        {
                            <dt>Main Phone</dt>
                            <dd>@Html.DisplayFor(modelItem => item.PhonePrimaryContact)</dd>
                        }

                        @if (item.BookingURL != null)
                        {
                            <dt>Booking/Membership</dt>
                            <dd>@Html.DisplayFor(modelItem => item.BookingURL)</dd>
                        }

                        @if (item.ContactEmail != null)
                        {
                            <dt>Contact Email</dt>
                            <dd>@Html.DisplayFor(modelItem => item.ContactEmail)</dd>
                        }

                        @if (item.FaultReportEmail != null)
                        {
                            <dt>Fault Report Email</dt>
                            <dd>@Html.DisplayFor(modelItem => item.FaultReportEmail)</dd>
                        }


                    </dl>

                </div>
            </div>
            
        }

    </div>
        
        
}
else
{
    <p>There are currently no known charging networks for this country. If you know one is missing, please @Html.ActionLink("Contact Us", "Contact", "About")</p>
}

<h2>Other Charging Providers</h2>
<p><a href="@Url.Action("Index", "POI", new { CountryIds = country.ID })">Charging Locations provided by Business Owners or Unknown Networks</a></p>