Website/OCM.Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using OCM.API.Common;
using OCM.API.Common.Model;
using System;

namespace OCM.MVC.Controllers
{
    public class AboutController : BaseController
    {
        IWebHostEnvironment _host;

        //
        // GET: /About/

        public AboutController(IWebHostEnvironment host)
        {
            _host = host;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }

        /// <summary>
        /// /Contact
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Guidance()
        {
            return View();
        }

        public ActionResult Funding()
        {
            return View();
        }

        public ActionResult DataSharing()
        {
            var countryList = new ReferenceDataManager().GetCountries(false);
            ViewBag.CountryList = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(countryList, "ID", "Title");
            return View(new DataSharingAgreement {  CountryID=2});
        }

        [HttpPost]
        [Authorize(Roles = "StandardUser")]
        public ActionResult DataSharing(DataSharingAgreement agreement)
        {

            var countryList = new ReferenceDataManager().GetCountries(false);
            ViewBag.CountryList = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(countryList, "ID", "Title");

            if (ModelState.IsValid)
            {

                var submissionManager = new SubmissionManager();
                bool savedOK = submissionManager.SubmitDataAgreement(agreement, (int)UserID);

                if (!savedOK)
                {
                    ViewBag.ErrorMessage = "Please check you have filled out all of the fields. All information is required.";
                }
                else
                {
                    ViewBag.Submitted = true;
                }


            }

            return View(agreement);
        }


        /// <summary>
        /// /contact/ post new contact us mesage
        /// </summary>
        /// <param name="album"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Contact(ContactSubmission contactSubmission)
        {
            if (ModelState.IsValid)
            {
                //check for spam bot by discarding submissions which populate phone field
                if (String.IsNullOrEmpty(contactSubmission.Phone))
                {
                    SubmissionManager submissionManager = new SubmissionManager();
                    bool sentOK = submissionManager.SubmitContactSubmission(contactSubmission);

                    if (!sentOK)
                    {
                        ViewBag.ErrorMessage = "There was a problem sending your message";
                    }
                }
                return RedirectToAction("ContactSubmitted");
            }

            return View(contactSubmission);
        }

        /// <summary>
        /// view shown after contact message submitted
        /// </summary>
        /// <returns></returns>
        public ActionResult ContactSubmitted()
        {
            return View();
        }
    }
}

Website/OCM.Web/Controllers/DevelopController.cs
using Microsoft.AspNetCore.Mvc;

namespace OCM.MVC.Controllers
{
    public class DevelopController : Controller
    {
        //
        // GET: /Develop/

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// /Develop/Apps
        /// </summary>
        /// <returns></returns>
        public ActionResult Apps()
        {
            return RedirectToActionPermanent("Index");
        }

        /// <summary>
        /// Show API Docs
        /// </summary>
        /// <returns></returns>
        public ActionResult API()
        {
            return View();
        }
    }
}

Website/OCM.Web/Controllers/POIController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using OCM.API.Common;
using OCM.API.Common.DataSummary;
using OCM.API.Common.Model;
using OCM.Core.Common;
using OCM.Core.Settings;
using OCM.MVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace OCM.MVC.Controllers
{
    public class POIController : BaseController
    {
        // GET: /POI/
        private IHostEnvironment _host;
        private IMemoryCache _cache;

        private CoreSettings _settings;
        public POIController(IHostEnvironment host, IMemoryCache memoryCache, IConfiguration config)
        {
            _host = host;
            _cache = memoryCache;

            _settings = GetSettingsFromConfig(config);
        }

        private CoreReferenceData GetCoreReferenceData()
        {
            return GetCoreReferenceDataAsync().Result;
        }

        private async Task<CoreReferenceData> GetCoreReferenceDataAsync()
        {
            if (_cache.TryGetValue("_coreRefData", out var refData))
            {
                return refData as CoreReferenceData;
            }
            else
            {
                using (var refDataManager = new OCM.API.Common.ReferenceDataManager())
                {
                    var result = await refDataManager.GetCoreReferenceDataAsync();
                    _cache.Set("_coreRefData", result);
                    return result;
                }
            }
        }

        public async Task<ActionResult> Index(POIBrowseModel filter)
        {
            if (filter?.ReferenceData == null)
            {
                if (filter == null)
                {
                    filter = new POIBrowseModel();
                    filter.ShowAdvancedOptions = true;
                }
                filter.ReferenceData = await GetCoreReferenceDataAsync();

            }

            var cpManager = new API.Common.POIManager();

            //dropdown selections of -1 represent an intended null selection, fix this by nulling relevant items
            filter.CountryIDs = this.ConvertNullableSelection(filter.CountryIDs);
            filter.LevelIDs = this.ConvertNullableSelection(filter.LevelIDs);
            filter.ConnectionTypeIDs = this.ConvertNullableSelection(filter.ConnectionTypeIDs);
            filter.OperatorIDs = this.ConvertNullableSelection(filter.OperatorIDs);
            filter.StatusTypeIDs = this.ConvertNullableSelection(filter.StatusTypeIDs);
            filter.UsageTypeIDs = this.ConvertNullableSelection(filter.UsageTypeIDs);
            filter.DataProviderIDs = this.ConvertNullableSelection(filter.DataProviderIDs);
            filter.SubmissionStatusTypeID = this.ConvertNullableSelection(filter.SubmissionStatusTypeID);

            filter.IncludeComments = true;

            if (IsRequestByRobot)
            {
                //force mirror db when browser is a robot
                filter.AllowMirrorDB = true;
                filter.AllowDataStoreDB = false;
            }

            if (!String.IsNullOrWhiteSpace(filter.Country))
            {
                //TODO: cache country id lookup
                using (var refData = new OCM.API.Common.ReferenceDataManager())
                {
                    var countrySelected = refData.GetCountryByName(filter.Country);
                    if (countrySelected != null)
                    {
                        filter.CountryIDs = new int[] { countrySelected.ID };
                    }
                }
            }
            else
            {
                //default to UK
                // if (filter.CountryIDs == null) filter.CountryIDs = new int[] { 1 };
            }

            filter.MaxResults = 100;

            if (!String.IsNullOrWhiteSpace(filter.SearchLocation))
            {
                if (filter.SearchLocation.ToUpper().StartsWith("OCM-")) filter.SearchLocation = filter.SearchLocation.Replace("OCM-", "");
                if (filter.SearchLocation.ToUpper().StartsWith("OCM")) filter.SearchLocation = filter.SearchLocation.Replace("OCM", "");

                if (IsNumeric(filter.SearchLocation.Trim()))
                {
                    int poiID = -1;
                    //treat numbers as OCM ref
                    if (int.TryParse(filter.SearchLocation.Trim(), out poiID))
                    {
                        filter.ChargePointIDs = new int[] { poiID };
                    }
                }
                else
                {
                    //attempt to geocode
                    var geocode = new GeocodingHelper(_settings);
                    string searchCountryName = null;
                    if (filter.CountryIDs != null && filter.CountryIDs.Count() > 0)
                    {
                        var searchCountry = filter.ReferenceData.Countries.FirstOrDefault(c => c.ID == filter.CountryIDs[0]);
                        searchCountryName = searchCountry.Title;
                    }

                    API.Common.Model.Extended.GeocodingResult position = null;

                    // FIXME: geocoding is disabled, find an laternative service to use
                    //geocode.GeolocateAddressInfo_Google(filter.SearchLocation.Trim() + (searchCountryName != null ? ", " + searchCountryName : ""));

                    if (filter.SearchLocation.Contains(","))
                    {
                        var vals = filter.SearchLocation.Split(',');
                        if (IsNumeric(vals[0]) && IsNumeric(vals[1]))
                        {
                            position = new API.Common.Model.Extended.GeocodingResult
                            {
                                Latitude = double.Parse(vals[0]),
                                Longitude = double.Parse(vals[1])
                            };
                        }
                    }
                    if (position != null)
                    {
                        filter.Latitude = position.Latitude;
                        filter.Longitude = position.Longitude;
                        if (filter.Distance == null) filter.Distance = 50;
                        filter.DistanceUnit = API.Common.Model.DistanceUnit.Miles;
                        //TODO: distance unit KM
                        //if (distanceunit == "km") searchfilters.DistanceUnit = API.Common.Model.DistanceUnit.KM;

                        ViewBag.FormattedAddress = position.Address ?? "";
                    }
                }
            }

            filter.POIList = (await cpManager.GetPOIListAsync((OCM.API.Common.APIRequestParams)filter, filter.ReferenceData)).ToList();
            return View(filter);
        }

        private int[] ConvertNullableSelection(int[] selectedItems)
        {
            if (selectedItems != null)
            {
                var list = selectedItems.ToList();
                list.RemoveAll(i => i == -1);
                if (list.Count > 0)
                {
                    return list.ToArray();
                }
            }
            return (int[])null;
        }

        private bool IsNumeric(string text)
        {
            Regex regex = new Regex(@"^[-+]?[0-9]*\.?[0-9]+$");
            return regex.IsMatch(text);
        }

        // GET: /POI/Details/5

        //[OutputCache(Duration=240, VaryByParam="id")]
        public async Task<ActionResult> Details(int id = 0, string layout = null, string status = null)
        {
            if (id <= 0) return RedirectToAction("Index");

            if (status != null) ViewBag.Status = status;

            OCM.API.Common.POIManager cpManager = new API.Common.POIManager();
            POIViewModel viewModel = new POIViewModel();

            var poi = await cpManager.Get(id, true, allowDiskCache: false, allowMirrorDB: true);
            if (poi != null)
            {
                ViewBag.FullTitle = "Location Details: OCM-" + poi.ID + " " + poi.AddressInfo.Title;

                List<LocationImage> imageList = null; // new OCM.MVC.App_Code.GeocodingHelper().GetGeneralLocationImages((double)poi.AddressInfo.Latitude, (double)poi.AddressInfo.Longitude);

                if (imageList != null)
                {
                    imageList = imageList.Where(i => i.Width >= 500).ToList();
                    ViewBag.ImageList = imageList.ToList();
                }

                viewModel.POI = poi;

                if (!IsRequestByRobot)
                {
                    viewModel.NewComment = new UserComment() { ChargePointID = poi.ID, CommentType = new UserCommentType { ID = 10 }, CheckinStatusType = new CheckinStatusType { ID = 0 } };

                    System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
                    sw.Start();
                    viewModel.POIListNearby = (await cpManager.GetPOIListAsync(new APIRequestParams { MaxResults = 10, Latitude = poi.AddressInfo.Latitude, Longitude = poi.AddressInfo.Longitude, Distance = 15, DistanceUnit = DistanceUnit.Miles, AllowMirrorDB = true })).ToList();
                    viewModel.POIListNearby.RemoveAll(p => p.ID == poi.ID); //don't include the current item in nearby POI list
                    sw.Stop();
                    System.Diagnostics.Debug.WriteLine(sw.ElapsedMilliseconds);

                    ViewBag.ReferenceData = new POIBrowseModel(await GetCoreReferenceDataAsync());

                    //get data quality report

                    //if (IsUserAdmin)
                    //{
                    viewModel.DataQualityReport = new DataAnalysisManager().GetDataQualityReport(poi);
                    //}

                    ViewBag.UserCanEditPOI = false;
                    if (IsUserSignedIn)
                    {

Website/OCM.Web/Controllers/StatsController.cs
using Microsoft.AspNetCore.Mvc;
using OCM.API.Common.DataSummary;
using OCM.MVC.Models;
using System;
using System.Linq;

namespace OCM.MVC.Controllers
{
    public class StatsController : Controller
    {
        // GET: Stats
        [ResponseCache(Duration = 60)]
        public ActionResult Index()
        {
            using (var dataSummary = new DataSummaryManager())
            {
                StatsModel model = new StatsModel();

                var dateTo = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1).AddDays(-1);
                var dateFrom = dateTo.AddYears(-1);

                model.TopContributors = dataSummary.GetTopNStats("UserPOIChangesLast90Days", 10, null);
                model.TopCommentators = dataSummary.GetTopNStats("UserCommentsLast90Days", 10, null);
                model.TopMediaItems = dataSummary.GetTopNStats("UserMediaLast90Days", 10, null);
                model.UserRegistrations = dataSummary.GetUserRegistrationStats(dateFrom, dateTo);
                model.UserEdits = dataSummary.GetUserEditSummary(dateFrom, dateTo);
                model.UserComments = dataSummary.GetUserCommentStats(dateFrom, dateTo);

                model.TotalActiveContributors = dataSummary.GetStatSingle("TotalChangeContributorsLast90Days");
                model.TotalActiveEditors = dataSummary.GetStatSingle("ActiveEditorsLast90Days");
                model.TotalCommentContributors = dataSummary.GetStatSingle("TotalCommentContributorsLast90Days");
                model.TotalPhotoContributors = dataSummary.GetStatSingle("TotalPhotoContributorsLast90Days");

                var countryStats = dataSummary.GetAllCountryStats();
                model.TotalLocations = countryStats.Sum(c => c.LocationCount);
                model.TotalStations = countryStats.Sum(c => c.StationCount);
                return View(model);
            }
        }
    }
}

Website/OCM.Web/Views/About/Contact.cshtml
@model OCM.API.Common.Model.ContactSubmission

@{
    ViewBag.Title = "Contact";
}

<h1>Contact Us</h1>
<p>
    To submit details for a new location use the Add Location menu option: <a href="https://map.openchargemap.io/">https://map.openchargemap.io</a>. To
suggest edits to an existing location browse to the location details and choose 'Edit'. Your edit will then be submitted for approval.
</p>

<p>
    For all other enquiries and comments please use <a href="https://community.openchargemap.org/">https://community.openchargemap.org/</a>
</p>
<p>Please note that we do not enter into individual agreements with organisations. If you wish to use the Open Charge Map data please refer to the <a href="@Url.Action("API","Develop")">API</a> documentation and terms</p>.

Website/OCM.Web/Views/About/Guidance.cshtml
@{
    ViewBag.Title = "Guidance for Submitters and Editors";

}

<script type="text/javascript" src="~/scripts/OCM/TableOfContents.js"></script>

<div class="row">

    <div class="col-sm-8 col-xs-12">
        <article>
            <section>
                <h1>Guidance for Contributors</h1>
                <h2 id="intro">Introduction</h2>
                <p>
                    The aim of the Open Charge Map project is to provide a reliable and well respected Open Data set for EV charging equipment locations globally. Data in OCM comes from two types of source: User Contributions and <a href="#dataimports">3rd Party Data Imports</a>. We rely on our contributors to do their best to provide quality information when manually providing and improving information.
                </p>
                <p>
                    This guidance exists to describe both optional and mandatory practises when contributing information to us.
                </p>
            </section>
            <section>

                <h2 id="intro">Guidance For All Contributors</h2>
                <h3 id="terms">Acceptance of Terms</h3>
                <p>
                    All information you submit (including charging equipment information, comments, check-ins and photos) to Open Charge Map is held by us and redistributed under an Open Data license. By submitting any information to us you are agreeing to these <a href="@Url.Action("Terms", "About")">terms</a>.
                    <h3 id="commentsandphotos">Contributing Comments, Check-In and Photos</h3>
                <p>
                    Adding a Check-In, Comment (which is the same as a Check-In but with your own comment) or Photo can make a huge difference to other people who find a charging location using Open Charge Map data, especially if your comment can help them plan their journey or avoid problems.
                    Using this feature you can provide useful information to others:
                    <ul>
                        <li>If the location is difficult to access.</li>
                        <li>If the equipment is in good working order.</li>
                        <li>What the parking spot looks like.</li>
                        <li>If the spot is regularly occupied (whether by EV's or other cars).</li>
                        <li>If their is a fault, you can report it - if we know the Operators contact details they will be emailed the fault report.</li>
                    </ul>
                    If you find the information for a location to be inaccurate in any way you can <a href="#edits">edit the details</a> yourself using either the OCM website or the OCM App on your mobile/tablet. Your changes will then wait in the <a href="#editqueue">Edit Queue</a> to be approved by an Editor for the relevant country.
                </p>

                <h3 id="edits">Submitting New Locations</h3>
                <p><strong>If possible you should encourage local charging networks in your country to provide data to us an an OCPI data feed. They gain free promotion to consumers of our data set (thousands of apps and services) and you then don't need to manually provide information. To do so they can fill out our @Html.ActionLink("Data Sharing Agreement", "DataSharing", "About") form. </strong></p>
                <p>
                    <ul>
                        <li>Ensure the location is not a duplicate of an existing listing.</li>
                        <li>Ensure the location is not a private residence (home). OCM does not accept information related to private individuals because we cannot provide the data protection required by law in many countries. This is because our data is widely redistributed.</li>
                        <li>Provide as much detail as possible without being verbose or opinionated - you can leave additional comments and photos etc once you have submitted the location.</li>
                        <li>
                            Follow your country/regional standards for Address information e.g.:
                            <ul>
                                <li>In the UK postcodes are uppercase and separated into two components.</li>
                                <li>In Australia the suburb is all uppercase.</li>
                            </ul>
                        </li>
                    </ul>
                </p>
                <h2 id="edits">Submitting Edits</h2>
                <p>You can edit the details of any location whether you are a normal user or a <a href="#country-editor">country editor</a>.</>
                <p>You should aim to make each listing as complete as possible. If a listing is sourced automatically you should consider whether you can notify the source of the information about required changes so that all other consumers of that information can be notified. Where this is not possible/practical you can edit the listing on Open Charge Map however future imports will no longer be automatically updated for that location.</p>
                <h3 id="edit-removinginfo">Removing Information</h3>
                <p>You should not remove information (equipment details, power specifications etc) if you cannot verify the accuracy of the information unless the original information does not make logical sense. Only information you know to be incorrect should be changed.</p>

                <h2 id="country-editor">Country Editor</h2>
                <p>If you have made a significant number of good submissions we may promote your account to Country Editor for the countries you are most active in. Country Editors can make changes which don't require further approval and they can approve changes submitted by other users.</p>
                <p>It is the responsibility of each country editor to ensure that submissions they approve are of a reasonable quality, do not introduce duplication and do not appear to be private residences (homes).</p>
                <p>It is not the responsibility of the country editor to validate that the equipment exists, this information can instead be provided by all users in the form of comments or edits using the app or website.</p>
                <p>It is the responsibility of all country editors to ensure they are following the latest guidance for their role (as presented and updated here). Failing to reasonably follow this guidance may result in the Country Editor role being removed from your account.</p>
                <h3 id="duplicates">Resolving Duplicates</h3>
                <p>
                    If you identify a duplicate listing you should resolve the duplicate as follows:
                </p>
                <p>
                    If comments or photos are present on one listing but not on the other then the listing with comments/photos is automatically the best one to keep (because it has user contributed information, unless the comment is 'this is a duplicate'). In this situation you should compare the information for the two listings and improve the listing with comments/photos as required, then delist the other location.

                </p>
                <p>If both listings are virtually identical with no comment/photos or other distinguishing features then you should delist the newest entry (with the highest OCM-ID reference).</p>
                <h3 id="newadditions">New Locations Awaiting Approval</h3>
                <p>The easiest way to review the locations awaiting approval is via the <a href="@Url.Action("Index", "POI", new { submissionstatustypeid = 1 })">New Locations Awaiting Approval</a> page. From there an editor can look at the details of the individual location, inspect the quality of the submission and approve it.</p>
                <h3 id="editqueue">The Edit Queue</h3>
                <p>The Edit Queue is where changes to existing locations await approval by an editor for the relevant country. The edit queue can show both new locations and edits to existing locations but is best suited to managing edits.</p>
                <h2 id="dataimports">3rd Party Data Imports</h2>
                <p>
                    Many government agencies and industry groups around the world provide EV charging location information as Open Data. These data sets can contain thousands of entries and are often a great source of additional information for the OCM data set.
                </p>
                <p>Where an import process has been created for OCM we periodically import from each data source, adding new locations and updating existing ones. If you wish to change one of these listings, they can do so using the normal Edit function.</p>
                <p>
                    When you edit a location from a 3rd Party Data Import the following process is followed:
                    <ul>
                        <li>The old listing is archived for future reference as a superceded POI.</li>
                        <li>We link the old POI with your new version in the OCM database.</li>
                        <li>From then on users only see the edited OCM version of the listing.</li>
                        <li>Subsequent data imports are ignored for that location. This means that improvements made by the 3rd Party will not be seen in the OCM listing and will need to be applied manually.</li>
                    </ul>
                </p>
            </section>
        </article>
    </div>
    <div class="col-sm-4 hidden-xs"><div id="toc" style="position:fixed;"></div></div>
</div>
<script type="text/javascript">
    $(function () {
        prepareTableOfContents();
    });
</script>

Website/OCM.Web/Views/About/Index.cshtml
@{
    ViewBag.Title = "About Open Charge Map";
}
<h2 data-localize="ocm.infoText.about.ourService">Our Service</h2>
<p data-localize="ocm.infoText.shortProjectSummary">Open Charge Map is a non-commercial, non-profit, electric vehicle data service hosted and supported by a community of businesses, charities, developers and interested parties around the world.</p>
@Html.Partial("_TermsLink")

<h2 data-localize="ocm.infoText.about.aim.title">Our Aim</h2>
<p data-localize="ocm.infoText.about.aim.p1">Our aim is to work with the community to develop and provide a high quality, public, free, open database of charging equipment locations globally.</p>
<p data-localize="ocm.infoText.about.aim.p2">
    Our goal is to avoid the proliferation of independent conflicting charging location maps/websites/applications
    and to provide (as much as possible) a reliable single point of reference for charging equipment location information.
    Instead of competing with other data providers we aim to cooperate with and provide services to them, in exchange for
    data sharing and de-duplication efforts.
</p>
<h2 data-localize="ocm.infoText.about.whyOCM.title">Why Use Open Charge Map?</h2>
<p data-localize="ocm.infoText.about.whyOCM.content">By using Open Charge Map and related apps you are helping to improve the information in the registry by providing peer review, edits, additions, comments, photos and by promoting the service to other users. The benefit of OCM over others providers is that OCM's purpose is to share information openly, whereas commercial providers have to keep their information to themselves (or within the confines of their own App etc.) in order to maintain a commercially marketable data set.</p>

<div>
    <h2 data-localize="ocm.infoText.about.funding.title">Funding</h2>
    <p data-localize="ocm.infoText.about.funding.p1">Open Charge Map is developed and operated by volunteers. If you can offer funding to support the project or to fund specific work please <a href="@Url.Action("Contact", "About")" data-localize-id="link-contact">get in touch</a>. More information on funding and project costs <a href="@Url.Action("Funding", "About")" data-localize-id="link-funding">is available</a>.</p>
    <h3>Sponsors</h3>
    <p>
        We are grateful to the following project sponsors:
        <ul>
            <li><a href="https://webprofusion.com">webprofusion.com</a> : Gold Sponsor</li>
            <li><a href="https://cardog.app/">https://cardog.app/</a> : Silver Sponsor</li>
        </ul>
    </p>
    <p>If you would like to become a sponsor to help us fund service infrastructure costs, you can directly purchase a sponsorship <a href="https://buy.stripe.com/5kA6ru2Xrb2W4RacMP">via Stripe</a> or join our community discussions </p>
</div>

<div class="row">

    <div class="col-md-12">
        <h2 data-localize="ocm.infoText.about.developersContributors.sectionTitle">Developers and Contributors</h2>
        <p data-localize="ocm.infoText.about.developersContributors.p1">Our <a href="https://github.com/openchargemap" data-localize-id="link_github">GitHub project</a> provides a conduit for external technical contributors to discuss and influence our system and plans. Our <a href="https://community.openchargemap.org/">community</a> forum is our primary means of exchanging ideas and gathering feedback from interested parties.</p>
        <p data-localize="ocm.infoText.about.developersContributors.p2">
            You can take a look at the lists of our main contributors of
            <a href="https://github.com/openchargemap/ocm-system/graphs/contributors" data-localize-id="link_code">code</a>
            and
            <a href="@Url.Action("Index", "Stats")" data-localize-id="link_data">data</a>.
        </p>
        <h2 data-localize="ocm.infoText.about.projectStats.sectionTitle">Project Stats</h2>

        <p data-localize="ocm.infoText.about.projectStats.general">General statistics for Open Charge Map <a href="@Url.Action("Index", "Stats")" data-localize-id="link">data and usage</a> are available.</p>
    </div>
</div>
<h2 data-localize="ocm.infoText.about.dataSources.title">Data Providers</h2>
<p data-localize="ocm.infoText.about.dataSources.p1">
    The data made available through the Open Charge Map system and related services is sourced from many locations and is often provided directly ("crowd sourced") by our users and those of apps using our services.
</p>
<p data-localize="ocm.infoText.about.dataSources.p2">Credit and our thanks goes to following major data sources currently included in our database:</p>
@{
    var providers = (List<OCM.API.Common.Model.DataProvider>)new OCM.API.Common.ReferenceDataManager().GetCoreReferenceData(new OCM.API.Common.APIRequestParams()).DataProviders;
}

@foreach (var provider in providers.Where(p => p.IsApprovedImport == true || p.IsOpenDataLicensed == true))
{
    <h4>@provider.Title</h4>
    <p>
        DataProviderID: @provider.ID <br>
        @(provider.WebsiteURL != null ? provider.WebsiteURL : "")
    </p>
    <p>
        <em>
            @(provider.License != null ? " License: " + @provider.License : "(not licensed)")
        </em>
    </p>
}